const TEAMS = [
  // Group A
  { id: 'mex',  name: 'Mexico',              flag: '🇲🇽', cc: 'mx',     confederation: 'CONCACAF', group: 'A', strength: 74, fifaRank: 14 },
  { id: 'rsa',  name: 'South Africa',        flag: '🇿🇦', cc: 'za',     confederation: 'CAF',      group: 'A', strength: 58, fifaRank: 60 },
  { id: 'kor',  name: 'South Korea',         flag: '🇰🇷', cc: 'kr',     confederation: 'AFC',      group: 'A', strength: 72, fifaRank: 25 },
  { id: 'cze',  name: 'Czech Republic',      flag: '🇨🇿', cc: 'cz',     confederation: 'UEFA',     group: 'A', strength: 76, fifaRank: 40 },
  // Group B
  { id: 'can',  name: 'Canada',              flag: '🇨🇦', cc: 'ca',     confederation: 'CONCACAF', group: 'B', strength: 72, fifaRank: 30 },
  { id: 'bih',  name: 'Bosnia & Herzegovina',flag: '🇧🇦', cc: 'ba',     confederation: 'UEFA',     group: 'B', strength: 68, fifaRank: 64 },
  { id: 'qat',  name: 'Qatar',               flag: '🇶🇦', cc: 'qa',     confederation: 'AFC',      group: 'B', strength: 55, fifaRank: 56 },
  { id: 'sui',  name: 'Switzerland',         flag: '🇨🇭', cc: 'ch',     confederation: 'UEFA',     group: 'B', strength: 79, fifaRank: 19 },
  // Group C
  { id: 'bra',  name: 'Brazil',              flag: '🇧🇷', cc: 'br',     confederation: 'CONMEBOL', group: 'C', strength: 91, fifaRank: 6  },
  { id: 'mar',  name: 'Morocco',             flag: '🇲🇦', cc: 'ma',     confederation: 'CAF',      group: 'C', strength: 76, fifaRank: 7  },
  { id: 'hai',  name: 'Haiti',               flag: '🇭🇹', cc: 'ht',     confederation: 'CONCACAF', group: 'C', strength: 52, fifaRank: 83 },
  { id: 'sco',  name: 'Scotland',            flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', cc: 'gb-sct', confederation: 'UEFA',     group: 'C', strength: 73, fifaRank: 42 },
  // Group D
  { id: 'usa',  name: 'United States',       flag: '🇺🇸', cc: 'us',     confederation: 'CONCACAF', group: 'D', strength: 76, fifaRank: 17 },
  { id: 'pry',  name: 'Paraguay',            flag: '🇵🇾', cc: 'py',     confederation: 'CONMEBOL', group: 'D', strength: 66, fifaRank: 41 },
  { id: 'aus',  name: 'Australia',           flag: '🇦🇺', cc: 'au',     confederation: 'AFC',      group: 'D', strength: 68, fifaRank: 27 },
  { id: 'tur',  name: 'Turkey',              flag: '🇹🇷', cc: 'tr',     confederation: 'UEFA',     group: 'D', strength: 77, fifaRank: 22 },
  // Group E
  { id: 'ger',  name: 'Germany',             flag: '🇩🇪', cc: 'de',     confederation: 'UEFA',     group: 'E', strength: 88, fifaRank: 10 },
  { id: 'cur',  name: 'Curaçao',             flag: '🇨🇼', cc: 'cw',     confederation: 'CONCACAF', group: 'E', strength: 50, fifaRank: 82 },
  { id: 'civ',  name: "Côte d'Ivoire",       flag: '🇨🇮', cc: 'ci',     confederation: 'CAF',      group: 'E', strength: 68, fifaRank: 33 },
  { id: 'ecu',  name: 'Ecuador',             flag: '🇪🇨', cc: 'ec',     confederation: 'CONMEBOL', group: 'E', strength: 70, fifaRank: 23 },
  // Group F
  { id: 'ned',  name: 'Netherlands',         flag: '🇳🇱', cc: 'nl',     confederation: 'UEFA',     group: 'F', strength: 86, fifaRank: 8  },
  { id: 'jpn',  name: 'Japan',               flag: '🇯🇵', cc: 'jp',     confederation: 'AFC',      group: 'F', strength: 78, fifaRank: 18 },
  { id: 'swe',  name: 'Sweden',              flag: '🇸🇪', cc: 'se',     confederation: 'UEFA',     group: 'F', strength: 75, fifaRank: 38 },
  { id: 'tun',  name: 'Tunisia',             flag: '🇹🇳', cc: 'tn',     confederation: 'CAF',      group: 'F', strength: 64, fifaRank: 45 },
  // Group G
  { id: 'bel',  name: 'Belgium',             flag: '🇧🇪', cc: 'be',     confederation: 'UEFA',     group: 'G', strength: 83, fifaRank: 9  },
  { id: 'egy',  name: 'Egypt',               flag: '🇪🇬', cc: 'eg',     confederation: 'CAF',      group: 'G', strength: 67, fifaRank: 29 },
  { id: 'irn',  name: 'Iran',                flag: '🇮🇷', cc: 'ir',     confederation: 'AFC',      group: 'G', strength: 65, fifaRank: 20 },
  { id: 'nzl',  name: 'New Zealand',         flag: '🇳🇿', cc: 'nz',     confederation: 'OFC',      group: 'G', strength: 56, fifaRank: 85 },
  // Group H
  { id: 'esp',  name: 'Spain',               flag: '🇪🇸', cc: 'es',     confederation: 'UEFA',     group: 'H', strength: 92, fifaRank: 2  },
  { id: 'cpv',  name: 'Cape Verde',          flag: '🇨🇻', cc: 'cv',     confederation: 'CAF',      group: 'H', strength: 60, fifaRank: 67 },
  { id: 'ksa',  name: 'Saudi Arabia',        flag: '🇸🇦', cc: 'sa',     confederation: 'AFC',      group: 'H', strength: 63, fifaRank: 61 },
  { id: 'uru',  name: 'Uruguay',             flag: '🇺🇾', cc: 'uy',     confederation: 'CONMEBOL', group: 'H', strength: 82, fifaRank: 16 },
  // Group I
  { id: 'fra',  name: 'France',              flag: '🇫🇷', cc: 'fr',     confederation: 'UEFA',     group: 'I', strength: 93, fifaRank: 3  },
  { id: 'sen',  name: 'Senegal',             flag: '🇸🇳', cc: 'sn',     confederation: 'CAF',      group: 'I', strength: 74, fifaRank: 15 },
  { id: 'irq',  name: 'Iraq',                flag: '🇮🇶', cc: 'iq',     confederation: 'AFC',      group: 'I', strength: 57, fifaRank: 57 },
  { id: 'nor',  name: 'Norway',              flag: '🇳🇴', cc: 'no',     confederation: 'UEFA',     group: 'I', strength: 78, fifaRank: 31 },
  // Group J
  { id: 'arg',  name: 'Argentina',           flag: '🇦🇷', cc: 'ar',     confederation: 'CONMEBOL', group: 'J', strength: 94, fifaRank: 1  },
  { id: 'alg',  name: 'Algeria',             flag: '🇩🇿', cc: 'dz',     confederation: 'CAF',      group: 'J', strength: 66, fifaRank: 28 },
  { id: 'aut',  name: 'Austria',             flag: '🇦🇹', cc: 'at',     confederation: 'UEFA',     group: 'J', strength: 74, fifaRank: 24 },
  { id: 'jor',  name: 'Jordan',              flag: '🇯🇴', cc: 'jo',     confederation: 'AFC',      group: 'J', strength: 55, fifaRank: 63 },
  // Group K
  { id: 'por',  name: 'Portugal',            flag: '🇵🇹', cc: 'pt',     confederation: 'UEFA',     group: 'K', strength: 88, fifaRank: 5  },
  { id: 'cod',  name: 'DR Congo',            flag: '🇨🇩', cc: 'cd',     confederation: 'CAF',      group: 'K', strength: 62, fifaRank: 46 },
  { id: 'uzb',  name: 'Uzbekistan',          flag: '🇺🇿', cc: 'uz',     confederation: 'AFC',      group: 'K', strength: 58, fifaRank: 50 },
  { id: 'col',  name: 'Colombia',            flag: '🇨🇴', cc: 'co',     confederation: 'CONMEBOL', group: 'K', strength: 80, fifaRank: 13 },
  // Group L
  { id: 'eng',  name: 'England',             flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', cc: 'gb-eng', confederation: 'UEFA',     group: 'L', strength: 89, fifaRank: 4  },
  { id: 'cro',  name: 'Croatia',             flag: '🇭🇷', cc: 'hr',     confederation: 'UEFA',     group: 'L', strength: 80, fifaRank: 11 },
  { id: 'gha',  name: 'Ghana',               flag: '🇬🇭', cc: 'gh',     confederation: 'CAF',      group: 'L', strength: 63, fifaRank: 73 },
  { id: 'pan',  name: 'Panama',              flag: '🇵🇦', cc: 'pa',     confederation: 'CONCACAF', group: 'L', strength: 58, fifaRank: 34 },
];

const SCORERS = [
  { name: 'Jonathan David',    team: 'Canada',        cc: 'ca',     goals: 3, assists: 1 },
  { name: 'Lionel Messi',      team: 'Argentina',     cc: 'ar',     goals: 3, assists: 1 },
  { name: 'Cyle Larin',        team: 'Canada',        cc: 'ca',     goals: 2, assists: 0 },
  { name: 'Elijah Just',       team: 'New Zealand',   cc: 'nz',     goals: 2, assists: 0 },
  { name: 'Erling Haaland',    team: 'Norway',        cc: 'no',     goals: 2, assists: 1 },
  { name: 'Folarin Balogun',   team: 'United States', cc: 'us',     goals: 2, assists: 0 },
  { name: 'Harry Kane',        team: 'England',       cc: 'gb-eng', goals: 2, assists: 1 },
  { name: 'Ismael Saibari',    team: 'Morocco',       cc: 'ma',     goals: 2, assists: 0 },
  { name: 'Johan Manzambi',    team: 'Switzerland',   cc: 'ch',     goals: 2, assists: 0 },
  { name: 'Kai Havertz',       team: 'Germany',       cc: 'de',     goals: 2, assists: 0 },
  { name: 'Kylian Mbappé',     team: 'France',        cc: 'fr',     goals: 2, assists: 1 },
  { name: 'Matheus Cunha',     team: 'Brazil',        cc: 'br',     goals: 2, assists: 0 },
  { name: 'Vinícius Júnior',   team: 'Brazil',        cc: 'br',     goals: 2, assists: 0 },
  { name: 'Yasin Ayari',       team: 'Sweden',        cc: 'se',     goals: 2, assists: 1 },
  { name: 'Alexander Isak',    team: 'Sweden',        cc: 'se',     goals: 1, assists: 0 },
  { name: 'Bradley Barcola',   team: 'France',        cc: 'fr',     goals: 1, assists: 0 },
  { name: 'Jamal Musiala',     team: 'Germany',       cc: 'de',     goals: 1, assists: 1 },
  { name: 'Jude Bellingham',   team: 'England',       cc: 'gb-eng', goals: 1, assists: 1 },
  { name: 'Marcus Rashford',   team: 'England',       cc: 'gb-eng', goals: 1, assists: 0 },
  { name: 'Raúl Jiménez',      team: 'Mexico',        cc: 'mx',     goals: 1, assists: 0 },
  { name: 'Rodrigo De Paul',   team: 'Argentina',     cc: 'ar',     goals: 1, assists: 0 },
  { name: 'Pedri',             team: 'Spain',         cc: 'es',     goals: 1, assists: 0 },
  { name: 'Deniz Undav',       team: 'Germany',       cc: 'de',     goals: 1, assists: 0 },
  { name: 'Crysencio Summerville', team: 'Netherlands', cc: 'nl',   goals: 1, assists: 0 },
  { name: 'Luis Díaz',         team: 'Colombia',      cc: 'co',     goals: 1, assists: 0 },
];

const PLAYERS = [
  // Argentina
  {
    id: 1, name: 'Lionel Messi', team: 'Argentina', teamFlag: '🇦🇷', cc: 'ar',
    position: 'FWD', age: 38, born: '24 Jun 1987', birthplace: 'Rosario, Argentina',
    club: 'Inter Miami', caps: 191, goals: 109, assists: 56, rating: 95, number: 10, image: '🐐',
    height: '1.70 m', foot: 'Left',
    bio: 'The greatest footballer of all time. Eight-time Ballon d\'Or winner and 2022 FIFA World Cup champion with Argentina. Known for his extraordinary dribbling, vision and goal-scoring ability.',
    highlights: ['2022 World Cup Champion', '2022 World Cup Golden Ball', '8× Ballon d\'Or', 'Copa América 2021', '4× UEFA Champions League'],
    wc_apps: 5, wc_goals: 13,
  },
  {
    id: 3, name: 'Rodrigo De Paul', team: 'Argentina', teamFlag: '🇦🇷', cc: 'ar',
    position: 'MID', age: 30, born: '24 May 1994', birthplace: 'Sarandí, Argentina',
    club: 'Atlético Madrid', caps: 68, goals: 8, assists: 20, rating: 85, number: 7, image: '🎯',
    height: '1.80 m', foot: 'Right',
    bio: 'The engine of Argentina\'s midfield. His tireless work rate and technical ability were crucial to Argentina\'s 2021 Copa América and 2022 World Cup wins.',
    highlights: ['2022 World Cup Champion', 'Copa América 2021', '2021 Conmebol Player of the Year'],
    wc_apps: 1, wc_goals: 0,
  },
  // France
  {
    id: 4, name: 'Kylian Mbappé', team: 'France', teamFlag: '🇫🇷', cc: 'fr',
    position: 'FWD', age: 26, born: '20 Dec 1998', birthplace: 'Paris, France',
    club: 'Real Madrid', caps: 89, goals: 48, assists: 28, rating: 94, number: 10, image: '💨',
    height: '1.78 m', foot: 'Right',
    bio: 'One of the fastest and most lethal forwards in history. Won the World Cup at just 19 with France in 2018 and scored a hat-trick in the 2022 final.',
    highlights: ['2018 World Cup Champion', '2022 WC Golden Boot', 'Ligue 1 top scorer 6×', 'UEFA Nations League 2021'],
    wc_apps: 2, wc_goals: 16,
  },
  {
    id: 5, name: 'Antoine Griezmann', team: 'France', teamFlag: '🇫🇷', cc: 'fr',
    position: 'FWD', age: 34, born: '21 Mar 1991', birthplace: 'Mâcon, France',
    club: 'Atlético Madrid', caps: 137, goals: 46, assists: 35, rating: 87, number: 7, image: '🎭',
    height: '1.76 m', foot: 'Left',
    bio: 'One of Europe\'s most consistent forwards for over a decade. Won the 2018 World Cup and scored in the 2022 final. Golden Boot at Euro 2016.',
    highlights: ['2018 World Cup Champion', 'Euro 2016 Golden Boot', '2 UEFA Europa League titles', 'La Liga 2021'],
    wc_apps: 3, wc_goals: 7,
  },
  {
    id: 6, name: 'Aurélien Tchouaméni', team: 'France', teamFlag: '🇫🇷', cc: 'fr',
    position: 'MID', age: 25, born: '16 Jan 2000', birthplace: 'Rouen, France',
    club: 'Real Madrid', caps: 38, goals: 5, assists: 4, rating: 86, number: 8, image: '🛡️',
    height: '1.87 m', foot: 'Right',
    bio: 'Dominant defensive midfielder who has quickly become a cornerstone of France\'s midfield. His physicality and passing range make him one of Europe\'s best.',
    highlights: ['2022 World Cup finalist', 'UEFA Champions League 2024', 'Ligue 1 2022'],
    wc_apps: 1, wc_goals: 1,
  },
  // England
  {
    id: 7, name: 'Jude Bellingham', team: 'England', teamFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', cc: 'gb-eng',
    position: 'MID', age: 21, born: '29 Jun 2003', birthplace: 'Stourbridge, England',
    club: 'Real Madrid', caps: 38, goals: 5, assists: 8, rating: 91, number: 10, image: '⭐',
    height: '1.86 m', foot: 'Right',
    bio: 'A generational talent who became one of the best players in the world before his 21st birthday. His energy, leadership and goal-scoring from midfield are extraordinary.',
    highlights: ['UEFA Champions League 2024', 'La Liga 2024', 'Bundesliga 2023', 'UEFA Euro 2024 finalist'],
    wc_apps: 1, wc_goals: 0,
  },
  {
    id: 8, name: 'Harry Kane', team: 'England', teamFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', cc: 'gb-eng',
    position: 'FWD', age: 31, born: '28 Jul 1993', birthplace: 'Walthamstow, England',
    club: 'Bayern Munich', caps: 97, goals: 68, assists: 18, rating: 90, number: 9, image: '👑',
    height: '1.88 m', foot: 'Right',
    bio: 'England\'s all-time top scorer and one of the most complete centre-forwards in history. A master of positioning, hold-up play and clinical finishing.',
    highlights: ['England all-time top scorer', '2018 WC Golden Boot', 'Premier League top scorer 3×', 'Bundesliga top scorer 2024'],
    wc_apps: 2, wc_goals: 8,
  },
  {
    id: 9, name: 'Phil Foden', team: 'England', teamFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', cc: 'gb-eng',
    position: 'MID', age: 25, born: '28 May 2000', birthplace: 'Stockport, England',
    club: 'Man City', caps: 42, goals: 10, assists: 9, rating: 88, number: 47, image: '🌟',
    height: '1.71 m', foot: 'Left',
    bio: 'The Stockport Iniesta — an academy product who became Man City\'s most important player. Won PFA Players\' Player of the Year 2024.',
    highlights: ['6× Premier League winner', '2023 Champions League', 'PFA POTY 2024', 'Euro 2024 finalist'],
    wc_apps: 1, wc_goals: 0,
  },
  // Portugal
  {
    id: 10, name: 'Cristiano Ronaldo', team: 'Portugal', teamFlag: '🇵🇹', cc: 'pt',
    position: 'FWD', age: 41, born: '5 Feb 1985', birthplace: 'Funchal, Portugal',
    club: 'Al Nassr', caps: 215, goals: 136, assists: 43, rating: 87, number: 7, image: '🐐',
    height: '1.87 m', foot: 'Right',
    bio: 'The most capped international player in history and record international goal scorer. Five Ballon d\'Or wins and a career of unprecedented individual achievement across three top leagues.',
    highlights: ['5× Ballon d\'Or', 'Euro 2016 Champion', '5× Champions League', 'Nations League 2019', 'Most intl goals ever'],
    wc_apps: 5, wc_goals: 8,
  },
  {
    id: 11, name: 'Bruno Fernandes', team: 'Portugal', teamFlag: '🇵🇹', cc: 'pt',
    position: 'MID', age: 31, born: '8 Sep 1994', birthplace: 'Maia, Portugal',
    club: 'Man United', caps: 78, goals: 22, assists: 31, rating: 88, number: 8, image: '🎯',
    height: '1.79 m', foot: 'Right',
    bio: 'Attacking midfielder who transformed Manchester United after joining in 2020. His long-range shooting, creativity and leadership have made him Portugal\'s key playmaker.',
    highlights: ['Nations League 2019', 'Premier League top assister', 'Serie A winner 2019', 'Europa League finalist'],
    wc_apps: 2, wc_goals: 3,
  },
  {
    id: 12, name: 'Bernardo Silva', team: 'Portugal', teamFlag: '🇵🇹', cc: 'pt',
    position: 'MID', age: 30, born: '10 Aug 1994', birthplace: 'Lisbon, Portugal',
    club: 'Man City', caps: 82, goals: 15, assists: 26, rating: 87, number: 10, image: '💫',
    height: '1.73 m', foot: 'Right',
    bio: 'One of the most technically gifted midfielders in the world. His pressing, dribbling and passing make him indispensable for both Man City and Portugal.',
    highlights: ['5× Premier League winner', '2023 Champions League', 'Nations League 2019', 'Ligue 1 2017'],
    wc_apps: 2, wc_goals: 1,
  },
  // Brazil
  {
    id: 14, name: 'Rodrygo', team: 'Brazil', teamFlag: '🇧🇷', cc: 'br',
    position: 'FWD', age: 23, born: '9 Jan 2001', birthplace: 'Osasco, Brazil',
    club: 'Real Madrid', caps: 38, goals: 12, assists: 8, rating: 86, number: 11, image: '⚡',
    height: '1.74 m', foot: 'Right',
    bio: 'A big-game player known for his clutch goals in the Champions League. His versatility and technical ability give Brazil another dimension in attack.',
    highlights: ['2× Champions League winner', '2 goals vs Man City in UCL semi 2023', 'La Liga 2024'],
    wc_apps: 1, wc_goals: 2,
  },
  {
    id: 15, name: 'Lucas Paquetá', team: 'Brazil', teamFlag: '🇧🇷', cc: 'br',
    position: 'MID', age: 26, born: '27 Aug 1997', birthplace: 'Rio de Janeiro, Brazil',
    club: 'West Ham', caps: 56, goals: 11, assists: 16, rating: 85, number: 10, image: '🌟',
    height: '1.80 m', foot: 'Left',
    bio: 'Creative attacking midfielder who carries the #10 burden for Brazil. Known for his technical brilliance, dribbling and ability to unlock defences.',
    highlights: ['Copa América 2019 winner', 'Ligue 1 champion 2022', 'Série A champion 2019'],
    wc_apps: 1, wc_goals: 1,
  },
  // Spain
  {
    id: 16, name: 'Pedri', team: 'Spain', teamFlag: '🇪🇸', cc: 'es',
    position: 'MID', age: 22, born: '25 Nov 2002', birthplace: 'Tegueste, Spain',
    club: 'Barcelona', caps: 42, goals: 7, assists: 12, rating: 88, number: 16, image: '🎨',
    height: '1.74 m', foot: 'Right',
    bio: 'The heir to Xavi and Iniesta. Pedri\'s positional awareness, passing and control under pressure at such a young age are remarkable. Euro 2024 champion.',
    highlights: ['Euro 2024 Champion', 'Nations League 2021', 'Copa del Rey 2021', 'Kopa Trophy 2022'],
    wc_apps: 1, wc_goals: 0,
  },
  {
    id: 17, name: 'Lamine Yamal', team: 'Spain', teamFlag: '🇪🇸', cc: 'es',
    position: 'FWD', age: 17, born: '13 Jul 2007', birthplace: 'Esplugues de Llobregat, Spain',
    club: 'Barcelona', caps: 22, goals: 7, assists: 9, rating: 87, number: 19, image: '🌠',
    height: '1.80 m', foot: 'Left',
    bio: 'The youngest player to score at a European Championship. A generational talent who burst onto the world stage at Euro 2024, winning the Golden Young Player award.',
    highlights: ['Euro 2024 Champion', 'Euro 2024 Young Player', 'Youngest Spain international', 'La Liga 2024-25'],
    wc_apps: 0, wc_goals: 0,
  },
  {
    id: 18, name: 'Álvaro Morata', team: 'Spain', teamFlag: '🇪🇸', cc: 'es',
    position: 'FWD', age: 32, born: '23 Oct 1992', birthplace: 'Madrid, Spain',
    club: 'AC Milan', caps: 76, goals: 35, assists: 17, rating: 84, number: 7, image: '⚽',
    height: '1.89 m', foot: 'Right',
    bio: 'Spain\'s captain and experienced target man. Despite being underrated, Morata consistently delivers on the big stage and led Spain to Euro 2024 glory.',
    highlights: ['Euro 2024 Champion', 'Nations League 2021', '2× Champions League', 'Serie A 2012'],
    wc_apps: 3, wc_goals: 5,
  },
  // Germany
  {
    id: 19, name: 'Florian Wirtz', team: 'Germany', teamFlag: '🇩🇪', cc: 'de',
    position: 'MID', age: 21, born: '3 May 2003', birthplace: 'Pulheim, Germany',
    club: 'Bayer Leverkusen', caps: 24, goals: 8, assists: 14, rating: 88, number: 10, image: '💎',
    height: '1.80 m', foot: 'Right',
    bio: 'The brightest young talent in German football. Led Leverkusen to an unbeaten Bundesliga title in 2023-24 and is widely seen as the future of German football.',
    highlights: ['Bundesliga 2023-24 (unbeaten)', 'DFB-Pokal 2024', 'Bundesliga POTY 2024', 'Euro 2024 semi-finalist'],
    wc_apps: 0, wc_goals: 0,
  },
  {
    id: 20, name: 'Jamal Musiala', team: 'Germany', teamFlag: '🇩🇪', cc: 'de',
    position: 'MID', age: 21, born: '26 Feb 2003', birthplace: 'Stuttgart, Germany',
    club: 'Bayern Munich', caps: 36, goals: 12, assists: 15, rating: 87, number: 14, image: '🌟',
    height: '1.80 m', foot: 'Right',
    bio: 'Silky attacking midfielder who chose Germany over England. His dribbling through tight spaces and goal-scoring threat from midfield make him one of the world\'s most exciting players.',
    highlights: ['8× Bundesliga champion', 'DFB-Pokal 2019', 'Champions League 2020', 'Euro 2024 semi-finalist'],
    wc_apps: 1, wc_goals: 1,
  },
  {
    id: 21, name: 'Kai Havertz', team: 'Germany', teamFlag: '🇩🇪', cc: 'de',
    position: 'FWD', age: 25, born: '11 Jun 1999', birthplace: 'Aachen, Germany',
    club: 'Arsenal', caps: 58, goals: 22, assists: 12, rating: 85, number: 7, image: '🎯',
    height: '1.89 m', foot: 'Right',
    bio: 'Versatile forward who scored the winning penalty in the 2021 Champions League final. Has found his best form at Arsenal as a false nine.',
    highlights: ['Champions League 2021', 'FA Cup 2023', 'DFB-Pokal 2017', 'PL runner-up 2024'],
    wc_apps: 2, wc_goals: 3,
  },
  // Morocco
  {
    id: 22, name: 'Achraf Hakimi', team: 'Morocco', teamFlag: '🇲🇦', cc: 'ma',
    position: 'DEF', age: 25, born: '4 Nov 1998', birthplace: 'Madrid, Spain',
    club: 'PSG', caps: 74, goals: 14, assists: 22, rating: 87, number: 2, image: '⚡',
    height: '1.81 m', foot: 'Right',
    bio: 'The best right-back in the world. His explosive speed and attacking contributions from defence are unmatched. Led Morocco to their historic 2022 WC semi-final.',
    highlights: ['2022 WC semi-finalist', 'Champions League 2020', 'Serie A 2021', 'AFCON finalist 2024'],
    wc_apps: 2, wc_goals: 1,
  },
  {
    id: 23, name: 'Hakim Ziyech', team: 'Morocco', teamFlag: '🇲🇦', cc: 'ma',
    position: 'MID', age: 32, born: '19 Mar 1993', birthplace: 'Dronten, Netherlands',
    club: 'Galatasaray', caps: 71, goals: 23, assists: 28, rating: 84, number: 7, image: '🎭',
    height: '1.81 m', foot: 'Left',
    bio: 'Creative winger with a magical left foot. Was key in Morocco\'s AFCON and World Cup campaigns with his creativity and dead-ball delivery.',
    highlights: ['2022 WC semi-finalist', 'AFCON 2024 finalist', 'Eredivisie top assister', 'FA Cup finalist 2022'],
    wc_apps: 2, wc_goals: 1,
  },
  {
    id: 24, name: 'Sofyan Amrabat', team: 'Morocco', teamFlag: '🇲🇦', cc: 'ma',
    position: 'MID', age: 27, born: '21 Aug 1996', birthplace: 'Huizen, Netherlands',
    club: 'Fiorentina', caps: 58, goals: 2, assists: 5, rating: 83, number: 4, image: '🛡️',
    height: '1.82 m', foot: 'Right',
    bio: 'The warrior at the heart of Morocco\'s midfield. His combative style and reading of the game were central to Morocco\'s incredible 2022 World Cup run.',
    highlights: ['2022 WC semi-finalist', 'WC 2022 Team of Tournament', 'Serie A with Fiorentina'],
    wc_apps: 2, wc_goals: 0,
  },
  // Netherlands
  {
    id: 25, name: 'Virgil van Dijk', team: 'Netherlands', teamFlag: '🇳🇱', cc: 'nl',
    position: 'DEF', age: 33, born: '8 Jul 1991', birthplace: 'Breda, Netherlands',
    club: 'Liverpool', caps: 68, goals: 8, assists: 5, rating: 88, number: 4, image: '🏰',
    height: '1.93 m', foot: 'Right',
    bio: 'The best centre-back in a generation. His physical dominance, leadership and composure on the ball transformed Liverpool into a defensive powerhouse.',
    highlights: ['2019 Champions League', '2020 Premier League', '2019 UEFA Men\'s Player of the Year', 'EURO 2024 semi-finalist'],
    wc_apps: 2, wc_goals: 1,
  },
  {
    id: 26, name: 'Cody Gakpo', team: 'Netherlands', teamFlag: '🇳🇱', cc: 'nl',
    position: 'FWD', age: 25, born: '7 May 1999', birthplace: 'Eindhoven, Netherlands',
    club: 'Liverpool', caps: 41, goals: 16, assists: 11, rating: 85, number: 11, image: '🔥',
    height: '1.89 m', foot: 'Right',
    bio: 'Tall, versatile forward who lit up the 2022 World Cup by scoring in the group stage. Transferred to Liverpool in January 2023 and has become a key player.',
    highlights: ['2022 WC 3 group stage goals', 'EURO 2024 semi-finalist', 'Premier League title contender 2024'],
    wc_apps: 1, wc_goals: 3,
  },
  // Japan
  {
    id: 27, name: 'Takehiro Tomiyasu', team: 'Japan', teamFlag: '🇯🇵', cc: 'jp',
    position: 'DEF', age: 25, born: '5 Nov 1998', birthplace: 'Fukuoka, Japan',
    club: 'Arsenal', caps: 45, goals: 1, assists: 3, rating: 82, number: 5, image: '🛡️',
    height: '1.87 m', foot: 'Right',
    bio: 'Versatile defender who can play right-back, centre-back or left-back. A key part of Arsenal\'s rebuilt defence and Japan\'s backline.',
    highlights: ['Serie A 2021 (Bologna)', 'Arsenal PL contender 2024', 'Japan WC R16 2022'],
    wc_apps: 2, wc_goals: 0,
  },
  {
    id: 28, name: 'Kaoru Mitoma', team: 'Japan', teamFlag: '🇯🇵', cc: 'jp',
    position: 'FWD', age: 27, born: '20 May 1997', birthplace: 'Kanagawa, Japan',
    club: 'Brighton', caps: 38, goals: 14, assists: 16, rating: 84, number: 10, image: '⚡',
    height: '1.78 m', foot: 'Left',
    bio: 'One of the most exciting wingers in the Premier League. His acceleration and dribbling ability in 1v1 situations makes him extremely difficult to defend.',
    highlights: ['Japan WC R16 2022', 'Brighton top performer 2023', 'J-League champion 2021'],
    wc_apps: 1, wc_goals: 1,
  },
  // Belgium
  {
    id: 29, name: 'Kevin De Bruyne', team: 'Belgium', teamFlag: '🇧🇪', cc: 'be',
    position: 'MID', age: 34, born: '28 Jun 1991', birthplace: 'Ghent, Belgium',
    club: 'Man City', caps: 106, goals: 26, assists: 48, rating: 90, number: 7, image: '🎯',
    height: '1.81 m', foot: 'Right',
    bio: 'The best midfielder in the world for most of the 2010s. His passing, vision and shooting are extraordinary. Architect of Man City\'s unprecedented domestic dominance.',
    highlights: ['6× Premier League', '2023 Champions League', 'PFA POTY 2020 & 2021', 'Belgium 3rd WC 2018'],
    wc_apps: 3, wc_goals: 2,
  },
  {
    id: 30, name: 'Romelu Lukaku', team: 'Belgium', teamFlag: '🇧🇪', cc: 'be',
    position: 'FWD', age: 31, born: '13 May 1993', birthplace: 'Antwerp, Belgium',
    club: 'Napoli', caps: 115, goals: 78, assists: 22, rating: 85, number: 9, image: '💪',
    height: '1.91 m', foot: 'Right',
    bio: 'Belgium\'s all-time top scorer and one of Europe\'s most physically imposing strikers. His combination of power, pace and finishing is formidable.',
    highlights: ['Belgium all-time top scorer', '3rd WC 2018', 'Serie A champion 2021', 'Europa League 2024'],
    wc_apps: 4, wc_goals: 10,
  },
  // Senegal
  {
    id: 31, name: 'Sadio Mané', team: 'Senegal', teamFlag: '🇸🇳', cc: 'sn',
    position: 'FWD', age: 33, born: '10 Apr 1992', birthplace: 'Sédhiou, Senegal',
    club: 'Al Nassr', caps: 103, goals: 38, assists: 24, rating: 84, number: 10, image: '🦁',
    height: '1.75 m', foot: 'Left',
    bio: 'AFCON 2022 champion and one of Africa\'s greatest ever footballers. Led Senegal to their first AFCON title and World Cup qualification with standout performances.',
    highlights: ['AFCON 2022 Champion', 'Champions League 2019', 'Premier League 2020', 'African Player of the Year 2022'],
    wc_apps: 2, wc_goals: 2,
  },
  {
    id: 32, name: 'Édouard Mendy', team: 'Senegal', teamFlag: '🇸🇳', cc: 'sn',
    position: 'GK', age: 32, born: '1 Mar 1992', birthplace: 'Montivilliers, France',
    club: 'Al Ahli', caps: 40, goals: 0, assists: 0, rating: 84, number: 1, image: '🧤',
    height: '1.97 m', foot: 'Right',
    bio: 'Towering goalkeeper who was world class during his time at Chelsea. Won the Champions League in his first season at the club.',
    highlights: ['Champions League 2021', 'UEFA Super Cup 2021', 'FIFA Club World Cup 2022', 'AFCON 2022'],
    wc_apps: 2, wc_goals: 0,
  },
  // USA
  {
    id: 33, name: 'Christian Pulisic', team: 'United States', teamFlag: '🇺🇸', cc: 'us',
    position: 'FWD', age: 27, born: '18 Sep 1998', birthplace: 'Hershey, Pennsylvania',
    club: 'AC Milan', caps: 73, goals: 28, assists: 18, rating: 83, number: 10, image: '⭐',
    height: '1.77 m', foot: 'Right',
    bio: 'Captain America. The first American to truly break through at the elite level of European football. His pace, dribbling and goal-scoring have made him USA\'s most important player.',
    highlights: ['Serie A top 3 2024', 'FA Cup 2022 (Chelsea)', 'Champions League finalist 2021', 'CONCACAF Gold Cup'],
    wc_apps: 2, wc_goals: 2,
  },
  {
    id: 34, name: 'Tyler Adams', team: 'United States', teamFlag: '🇺🇸', cc: 'us',
    position: 'MID', age: 25, born: '14 Feb 1999', birthplace: 'Wappingers Falls, NY',
    club: 'Bournemouth', caps: 47, goals: 2, assists: 6, rating: 80, number: 4, image: '🛡️',
    height: '1.78 m', foot: 'Right',
    bio: 'Tenacious defensive midfielder and USMNT captain. His reading of the game and ability to win the ball back quickly make him the heartbeat of the American side.',
    highlights: ['Bundesliga champion 2021-22 (Leipzig)', 'DFB-Pokal 2022', 'WC 2022 R16'],
    wc_apps: 1, wc_goals: 0,
  },
  // Croatia
  {
    id: 35, name: 'Luka Modrić', team: 'Croatia', teamFlag: '🇭🇷', cc: 'hr',
    position: 'MID', age: 40, born: '9 Sep 1985', birthplace: 'Zadar, Croatia',
    club: 'Real Madrid', caps: 176, goals: 25, assists: 38, rating: 86, number: 10, image: '👑',
    height: '1.72 m', foot: 'Right',
    bio: '2018 Ballon d\'Or winner and one of the greatest midfielders of all time. Led Croatia to the 2018 World Cup final and 2022 third place. Still performing at the highest level.',
    highlights: ['2018 Ballon d\'Or', '6× Champions League', '2018 WC finalist', '2022 WC 3rd', 'WC 2018 Golden Ball'],
    wc_apps: 5, wc_goals: 4,
  },
  {
    id: 36, name: 'Ivan Perišić', team: 'Croatia', teamFlag: '🇭🇷', cc: 'hr',
    position: 'MID', age: 36, born: '2 Feb 1989', birthplace: 'Split, Croatia',
    club: 'Hajduk Split', caps: 130, goals: 34, assists: 29, rating: 82, number: 4, image: '⚽',
    height: '1.87 m', foot: 'Both',
    bio: 'One of Croatia\'s most important players for over a decade. Scored in the 2018 WC final and was key in 2022. A technically gifted wide midfielder with great delivery.',
    highlights: ['2018 WC finalist', '2022 WC 3rd', 'Champions League 2019 (runner-up)', 'Bundesliga 2022'],
    wc_apps: 4, wc_goals: 6,
  },
  // Colombia
  {
    id: 37, name: 'James Rodríguez', team: 'Colombia', teamFlag: '🇨🇴', cc: 'co',
    position: 'MID', age: 33, born: '12 Jul 1991', birthplace: 'Cúcuta, Colombia',
    club: 'Rayo Vallecano', caps: 101, goals: 29, assists: 37, rating: 83, number: 10, image: '🌟',
    height: '1.80 m', foot: 'Left',
    bio: 'Won the 2014 World Cup Golden Boot with stunning goals and assists. His left foot and playmaking vision helped Colombia reach the quarter-finals in Brazil.',
    highlights: ['2014 WC Golden Boot', 'Copa América runner-up 2016', 'La Liga 2012', 'Ligue 1 2014'],
    wc_apps: 2, wc_goals: 6,
  },
  // South Korea
  {
    id: 39, name: 'Son Heung-min', team: 'South Korea', teamFlag: '🇰🇷', cc: 'kr',
    position: 'FWD', age: 33, born: '8 Jul 1992', birthplace: 'Chuncheon, South Korea',
    club: 'Tottenham', caps: 118, goals: 50, assists: 34, rating: 87, number: 7, image: '⚡',
    height: '1.83 m', foot: 'Left',
    bio: 'Asia\'s greatest footballer. Premier League Golden Boot winner (joint, 2022) and Tottenham\'s all-time top scorer in European football. His pace, finishing and work rate are elite.',
    highlights: ['PL Golden Boot 2022 (joint)', 'Spurs all-time European top scorer', 'Asian footballer of the year 4×', 'WC 2022 R16'],
    wc_apps: 3, wc_goals: 3,
  },
  // Denmark
  {
    id: 40, name: 'Christian Eriksen', team: 'Denmark', teamFlag: '🇩🇰', cc: 'dk',
    position: 'MID', age: 33, born: '14 Feb 1992', birthplace: 'Middelfart, Denmark',
    club: 'Man United', caps: 133, goals: 44, assists: 64, rating: 84, number: 10, image: '💫',
    height: '1.82 m', foot: 'Right',
    bio: 'One of football\'s most inspiring stories — returned to the pitch after cardiac arrest at Euro 2020 to play at the 2022 World Cup. A creative genius with extraordinary passing range.',
    highlights: ['Euro 2020 survivor', 'Premier League 2021 (Leicester)', 'Serie A 2021 (Inter)', 'Danish Player of Year 8×'],
    wc_apps: 3, wc_goals: 3,
  },
];
